name: "Pull Request checks"

on:
    pull_request:

permissions: read-all

jobs:
    validate-pr-title:
        name: Validate PR title
        runs-on: ubuntu-latest
        steps:
            -   uses: amannn/action-semantic-pull-request@48f256284bd46cdaab1048c3721360e808335d50 # v6
                env:
                    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    code-analysis:
        name: Code analysis
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout
                uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
            -   name: Set up php 8.5
                uses: shivammathur/setup-php@f3e473d116dcccaddc5834248c87452386958240 # 2.37.2
                with:
                    php-version: '8.5'
            -   name: Validate composer.json
                run: composer validate --strict
            -   name: Install dependencies
                run: composer install --prefer-dist --no-interaction
            -   name: Composer check platform requirements
                run: composer check-platform-reqs
            -   name: Security check
                run: composer audit
            -   name: Check workflow files
                uses: devops-actions/actionlint@9fb9c192862f19e684586ca84b500461bcd8a541 # v0.1.12
