name: release-please

on:
    push:
        branches:
            - master

permissions:
    contents: write
    pull-requests: write

jobs:
    release-please:
        runs-on: ubuntu-latest
        steps:
            -   uses: googleapis/release-please-action@a02a34c4d625f9be7cb89156071d8567266a2445 # v4
