name: Tests
on: [ push, pull_request ]
permissions: read-all
jobs:
    tests:
        name: Symfony ${{ matrix.symfony-version }}
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
            matrix:
                include:
                    -   symfony-version: 7.4-lowest
                        install-command: composer update --prefer-lowest --prefer-stable --with-all-dependencies --no-interaction
                    -   symfony-version: 8.x-highest
                        install-command: composer update --prefer-stable --with-all-dependencies --no-interaction
        steps:
            -   name: Checkout
                uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
            -   name: Set up php 8.5
                uses: shivammathur/setup-php@f3e473d116dcccaddc5834248c87452386958240 # 2.37.2
                with:
                    php-version: '8.5'
            -   name: Validate composer.json
                run: composer validate --strict
            -   name: Install dependencies
                run: ${{ matrix.install-command }}
            -   name: Composer check platform requirements
                run: composer check-platform-reqs
            -   name: Run quality checks
                run: composer qa
